spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://root:Ohv9fGuNgd1SdeQo4n3qfmhREtI0GhhG2hj6cl6Vw8OquYf-@a5789fc8-94a8-4040-a7ec-d1b099627419.asia-south1.firestore.goog:443/db-capstone?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}