spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://root:qTpoipBVDPitXfEH9HFbWd7SRMw13RMrHR5c2xpRzH_pxBOZ@fc015d2a-58cd-4630-b142-59b34e94c61d.asia-south1.firestore.goog:443/db-capstone-1?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}